# Generated by Django 6.0.3 on 2026-04-05 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nome da Marca'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=600, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fragrance',
            field=models.CharField(choices=[('WO', 'Wood'), ('FL', 'Floral'), ('CI', 'Citrus'), ('OR', 'Oriental'), ('FR', 'Fruity')], max_length=2, verbose_name='Fragrância'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome do Produto'),
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('sku_code', models.CharField(max_length=50, unique=True, verbose_name='Código SKU')),
                ('concentration', models.CharField(choices=[('EDC', 'Eau de Cologne'), ('EDT', 'Eau de Toilette'), ('EDP', 'Eau de Parfum'), ('PAR', 'Parfum')], max_length=3, verbose_name='Concentração')),
                ('volume_ml', models.PositiveIntegerField(verbose_name='Volume em ml')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'SKUs',
            },
        ),
    ]
