# Generated by Django 6.0.3 on 2026-04-05 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='Imagem')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'ordering': ['display_order'],
            },
        ),
    ]
