# Generated by Django 6.0.3 on 2026-06-16 18:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando Pagamento'), ('PAID', 'Pagamento Aprovado'), ('PREPARING', 'Em Preparação'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregue'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Total')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('shipping_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serviço de Entrega')),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Frete')),
                ('delivery_days', models.PositiveIntegerField(default=7, verbose_name='Prazo de Entrega (Dias)')),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Rastreio')),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cupom Utilizado')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Desconto')),
                ('payment_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação do Pagamento')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.address', verbose_name='Endereço de Entrega')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Preço Unitário na Compra')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.sku', verbose_name='SKU do Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('reason', models.CharField(max_length=100, verbose_name='Motivo')),
                ('action', models.CharField(max_length=100, verbose_name='Procedimento (Crédito/Estorno)')),
                ('description', models.TextField(verbose_name='Descrição do Problema')),
                ('media', models.ImageField(blank=True, null=True, upload_to='returns/%Y/%m/', verbose_name='Mídia (Foto)')),
                ('status', models.CharField(default='PENDENTE', max_length=50, verbose_name='Status da Devolução')),
                ('items', models.ManyToManyField(to='orders.orderitem', verbose_name='Itens Devolvidos')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Solicitação de Devolução',
                'verbose_name_plural': 'Solicitações de Devolução',
                'ordering': ['-created_at'],
            },
        ),
    ]
