# Generated by Django 6.0.3 on 2026-05-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shippingmethod_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação do Pagamento'),
        ),
    ]
