# Generated by Django 6.0.3 on 2026-05-31 21:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_approved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('reason', models.CharField(max_length=100, verbose_name='Motivo')),
                ('action', models.CharField(max_length=100, verbose_name='Procedimento (Crédito/Estorno)')),
                ('description', models.TextField(verbose_name='Descrição do Problema')),
                ('media', models.ImageField(blank=True, null=True, upload_to='returns/%Y/%m/', verbose_name='Mídia (Foto)')),
                ('status', models.CharField(default='PENDENTE', max_length=50, verbose_name='Status da Devolução')),
                ('items', models.ManyToManyField(to='orders.orderitem', verbose_name='Itens Devolvidos')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Solicitação de Devolução',
                'verbose_name_plural': 'Solicitações de Devolução',
                'ordering': ['-created_at'],
            },
        ),
    ]
