# Generated by Django 6.0.3 on 2026-06-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
