# Generated by Django 6.0.3 on 2026-06-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cupom Utilizado'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Prazo de Entrega (Dias)'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Desconto'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serviço de Entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Frete'),
        ),
    ]
